### PR TITLE
[wip] feat: sudoswap adapter

### PR DESCRIPTION
**Pull request by oritwoen**
resolve: https://github.com/dappradar/nft-sales-adapters/issues/89

I'm in the process of finishing the adapter. Tests pass correctly. All data is also well updated.

**_All that's left is to update the prices accordingly._**

I used the logs as universal invariable data on NFT transfer. So here the data is always up to date and you don't need to parse from the function arguments.

### CODE REVIEW

**Comment by adistanisha** [comment]
very nice and good sudoswap

**Comment by opmklinh** [comment]
I think the fee should be reduced for NFT listing, because I think gas is relatively high compared to the common ground

**Comment by Binhan01** [comment]
I also think that the cost barrier is also an obstacle for the development of NFT on sudoswap

**Comment by LJMStark** [comment]
test

**Comment by dragosdydy** [comment]
Thanks @0ri2N - let us know when you believe this is done. If you have any questions, feel free to ask here or in our [Discord](https://dappradar.com/discord) at #developers

**Comment by jeaven007** [comment]
All that's left is to update the prices accordingly.sudoswap

**Comment by oritwoen** [comment]
Adapter merged in another PR: https://github.com/dappradar/nft-sales-adapters/pull/140. I close.

**Pull request closed without merging**
