### PR TITLE
Kalao NFT marketplaces data tracking

### PR DESCRIPTION
**Pull request by kentmaster373**

### CODE REVIEW

**Review by liutaurasjanuskas — CHANGES_REQUESTED** [review]
It's not working. Fix the structure.

**Comment by halimsk786** [comment]
It's not working. Fix

**Comment by Nikkydrop** [comment]
It's not working. Fix

**Review by liutaurasjanuskas — CHANGES_REQUESTED** [review]
Please, fix the structure or we'll close the PR.

**Pull request closed without merging**
