### PR TITLE
Create nft

### PR DESCRIPTION
**Pull request by Aelx341**
0x639dfa62C529158e361E4D6C3446a8A95D5dBA6B

### CODE REVIEW

**Comment by mohamaddez** [comment]
Say HI

**Comment by peelo11** [comment]
OK

**Comment by AliSaa3a** [comment]
Nice ! Bought Some !

**Comment by BassLee777** [comment]
gm

**Comment by ysmry** [comment]
h

**Comment by liutaurasjanuskas** [comment]
No changes.

**Pull request closed without merging**
