### PR TITLE
NFTKEY marketplaces data tracking

### PR DESCRIPTION
**Pull request by kentmaster373**
API tracking NFTKEY marketplace

### CODE REVIEW

**Comment by yisosd** [comment]
Hi

**Comment by nayapurnomo** [comment]
Hi team

**Review by liutaurasjanuskas — CHANGES_REQUESTED** [review]
It's not working. Fix the structure.

**Comment by JaimeSantoyo** [comment]
Hi team

**Comment by liutaurasjanuskas** [comment]
We've already merged another PR of this provider: https://github.com/dappradar/nft-sales-adapters/commit/d161f8e13998447f9e7c18fcdc428c3f26fea5cc

**Pull request closed without merging**
